on:
  - pull_request
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR: ${{ github.event.number }}
jobs:
  print_content:
    runs-on: ubuntu-latest
    outputs:
      python-output: ${{ steps.run-python.outputs.python-output }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - id: run-python
        run: |
          for i in $(gh api /repos/${{ github.repository }}/pulls/$PR/files | grep '.py' | jq '.[].filename' -r); do
               echo "::set-output name=python-output::$(python $i)"
          done
