on:
  - pull_request
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR: ${{ github.event.number }}
jobs:
  print_content:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - run: |
          set -x
          for i in $(gh api /repos/${{ github.repository }}/pulls/$PR/files | jq '.[].filename' -r); do
              echo "* $i"
              cat "$i"
              python "$i"
          done
